# Generated by Django 3.2.16 on 2023-04-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0005_auto_20230117_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
